### ISSUE TITLE
Disallow folders with one file

### ISSUE THREAD

**Issue by capaj** [benawad/destiny#18]
For me, having only a single file sitting in directory is not nice.
For example in this repo: https://github.com/benawad/butler-cli/tree/9ad6e4c11ee096314402060f541047253336c5e1/src/index/formatFileStructure/syncFileSystem/fixImports

I would prefer if butler places the `makeImportPath.ts` into `syncFileSystem` folder next to `fixImports.ts`.

If you could add this `disallow-leaf-folders-with-one-file` config that would be just great! WDYT?

**Comment by AnatoleLucet** [comment]
I wouldn't recommend doing that in a "managed by hand" fractal structure since it involve to move `makeImportPath.ts` to a new folder if you want to add another deps to`fixImports.ts`. But because this is now managed by Butler, he could move `makeImportPath.ts` in a new `fixImports/` folder for us. So yeah, why not!

**Comment by AnatoleLucet** [comment]
Anyone having a short name idea for this option?
I though about `singleFile`/`--single--file` but it's not that self explanatory...

**Comment by sQVe** [comment]
I think `--move-only-child` or something similar is quite explanatory.

**Comment by sQVe** [comment]
`--rename-only-child` is even better I think.
